local builtin = require("telescope.builtin")

return {
	{ "grn",  vim.lsp.buf.rename,                                                    { desc = "renomear" } },
	{ "gra",          vim.lsp.buf.code_action,                                               { desc = "Busca ação" } },
	{ "grr",          builtin.lsp_references,                                                { desc = "vai para referencia" } },
	{ "gri",          builtin.lsp_implementations,                                           { desc = "vai para a implementação" } },
	{ "grd",          builtin.lsp_definitions,                                               { desc = "vai para definição" } },
	{ "grD",          vim.lsp.buf.declaration,                                               { desc = "vai para declaração" } },
	{ "gO",						builtin.lsp_document_symbols,                                          { desc = "documento dos simbolos" } },
	{"gW",						builtin.lsp_dynamic_workspace_symbols, { desc = "Open Workspace Symbols"}},
	{ "grt",          builtin.lsp_type_definitions,                                          { desc = "vai para definição de tipo" } },

	{ "<C-p>",       function() vim.diagnostic.jump({ forward = false }) end,               { desc = "Diagnóstico anterior" } },
	{ "<C-n>",       function() vim.diagnostic.jump({ forward = true }) end,                { desc = "Próximo diagnóstico" } },
	{ "<C-k>",       vim.lsp.buf.signature_help,                                            { desc = "mostra assinatura de ajuda" } },
	{ "<leader>ct",  vim.lsp.buf.type_definition,                                           { desc = "vai para definição do tipo" } },
	{ "<leader>cD",  vim.lsp.buf.declaration,                                               { desc = "vai para declaração" } },
	{ "<leader>cd",  vim.lsp.buf.definition,                                                { desc = "vai para definição" } },
	{ "<leader>cR",  vim.lsp.buf.references,                                                { desc = "vai para referencia" } },
	{ "<leader>ci",  vim.lsp.buf.implementation,                                            { desc = "vai para implementação" } },
	{ "<leader>clr", vim.lsp.stop_client,                                                   { desc = "reinicia" } },
	{ "<leader>cls", vim.lsp.start,                                                         { desc = "inicia" } },
	{ "<leader>cd[", function() vim.diagnostic.jump({ forward = false }) end,               { desc = "Diagnóstico anterior" } },
	{ "<leader>cd]", function() vim.diagnostic.jump({ forward = true }) end,                { desc = "Próximo diagnóstico" } },
	{ "<leader>cdp", function() vim.diagnostic.jump({ forward = false }) end,               { desc = "Diagnóstico anterior" } },
	{ "<leader>cdn", function() vim.diagnostic.jump({ forward = true }) end,                { desc = "Próximo diagnóstico" } },
	{ "<leader>ol", "<cmd>LspInfo<cr>", { desc = "Lsp" } },
	{ "<leader>l2", "<cmd>LspLog<cr>", { desc = "Lsp" } },
}
