return {
	"m4xshen/smartcolumn.nvim",
	event = { "BufEnter", "TextChanged", "TextChangedI" },
	opts = {
		colorcolumn = { "80", "100" },
		scope = "line",
		custom_colorcolumn = {
			python = "79",
		},
		disabled_filetypes = {
			"alpha",
			"dashboard",
			"dap-repl",
			"dapui_scopes",
			"dapui_breakpoints",
			"dapui_stacks",
			"dapui_watches",
			"dap-terminal",
			"dapui_console",
			"help",
			"lazy",
			"markdown",
			"mason",
			"neogitstatus",
			"neo-tree",
			"NvimTree",
			"Outline",
			"lir",
			"oil",
			"packer",
			"spectre_panel",
			"startify",
			"startup",
			"toggleterm",
			"Trouble",
		},
	},
}
