return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	dependencies = "nvim-tree/nvim-web-devicons",
	opts = {
		delay = 0,
		win = {
			border = "rounded",
		},
		spec = {
			{ "<leader>a", group = "avante" },
			{ "<leader>c", group = "Codigo", mode = { "n", "x" } },
			{ "<leader>d", group = "Documentação" },
			{ "<leader>g", group = "Git/Hunk" },
			{ "<leader>l", group = "logs" },
			{ "<leader>s", group = "Pesquisa" },
			{ "<leader>q", group = "fecha sessão" },
			{ "<leader>p", group = "Projeto" },
			{ "<leader>o", group = "abrir" },
			{ "<leader>w", group = "Janela" },
		},
		icons = {
			mappings = false,
			colors = false,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},
	},
}
