return function()
	local configs = require("nvim-treesitter.configs")

	configs.setup({
		ensure_installed = {
			"awk",
			"bash",
			"c",
			"css",
			"csv",
			"dockerfile",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"go",
			"goctl",
			"godot_resource",
			"gomod",
			"gosum",
			"gotmpl",
			"gowork",
			"hjson",
			"html",
			"javascript",
			"json",
			"json5",
			"jsonc",
			"lua",
			"luadoc",
			"make",
			"markdown",
			"markdown_inline",
			"nginx",
			"passwd",
			"prisma",
			"query",
			"rust",
			"sql",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
	})
end
