return {
	ensure_installed = {
		"lua",
		"go",
		"java",
		"nix",
		"c",
		"cpp",
		"html",
		"css",
		"markdown",
		"markdown_inline",
	},
	sync_install = true,
	auto_install = true,
	TSUpdate = true,
	parser_install_dir = nil,
	ignore_install = {},
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = true,
	},
	indent = { enable = true },
	modules = {},
}
