local wk = require("which-key")

wk.setup({
	show_help = false,
	spec = {
		{ "<leader>b", group = "buffer" },
		{ "<leader>c", group = "code" },
		{ "<leader>cd", group = "debugger" },
		{ "<leader>d", group = "dap" },
		-- { "<leader>f", group = "file" },
		{ "<leader>g", group = "git" },
		{ "<leader>h", group = "help" },
		{ "<leader>i", group = "insert" },
		{ "<leader>m", group = "moviment" },
		{ "<leader>n", group = "notes" },
		{ "<leader>o", group = "open" },
		{ "<leader>p", group = "project" },
		{ "<leader>q", group = "quit/session" },
		{ "<leader>s", group = "search" },
		{ "<leader>t", group = "toggle" },
		{ "<leader>w", proxy = "<c-w>", group = "window" },
	},
	win = {
		border = "rounded",
		padding = { 0, 0 },
		height = { min = 8, max = 15 },
		title = true,
		title_pos = "left",
	},
	layout = {
		width = { min = 40, max = 80 },
		spacing = 2,
	},
	icons = {
		breadcrumb = "-",
		separator = ":",
		mappings = false,
		keys = {
			Up = "up",
			Down = "down",
			Left = "left",
			Right = "right",
			C = "C",
			M = "M",
			D = "D",
			S = "S",
			CR = "ENTER",
			Esc = "ESC",
			ScrollWheelDown = "<wheel-down>",
			ScrollWheelUp = "<wheel-up",
			BS = "BACK",
			Space = "SPC",
			Tab = "TAB",
			F1 = "<f1>",
			F2 = "<f2>",
			F3 = "<f3>",
			F4 = "<f4>",
			F5 = "<f5>",
			F6 = "<f6>",
			F7 = "<f7>",
			F8 = "<f8>",
			F9 = "<f9>",
			F10 = "<f10>",
			F11 = "<f11>",
			F12 = "<f12>",
		},
	},
})
